site_name: Sistema de Inventario
theme:
  name: material
  language: es
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: teal
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: lime
  font:
    text: Roboto
    code: Roboto Mono
  favicon: img/favicon.png
  logo: img/logo.png
  features:
    - navigation.tabs
    - navigation.top
    - navigation.footer
    - content.code.annotate
    - content.tabs.link

nav:
  - Inicio: index.md
  - Acerca del sistema: about.md
  - Licencia: license.md
  - Guía de Usuario:
      - Primeros pasos: user-guide/getting-started.md
      - Configuración: user-guide/configuration-options.md

markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - toc:
      permalink: "#"

plugins:
  - search
  - git-revision-date-localized:
      fallback_to_build_date: true
      locale: es
      type: date

